### ISSUE TITLE
tasks and hint system 

### ISSUE THREAD

**Issue by dcsan** [dcsan/xbot#13]
step through hints with a few answers

```
tasks:
  - name: task1
     title: Clean up
     hints: 
        - the tannoy said to have a wash
        - you'll need some soap
        - It might be hidden near the sink
```

So the user's goal is to step through those tasks

they can ask for a hint, but it will cost some points
this comes off their score at the end (we track how many "hints" they used up)
