### ISSUE TITLE
switch / case clause

### ISSUE THREAD

**Issue by dcsan** [dcsan/xbot#20]
allow for multiple IF conditions to be met

```
        switch:
          - case: a.b = no
            then:
              reply: you dont have A
          - case: b.c = xx
            then:
              reply: you dont have 
```

or

```
        switch:
          - if: 
              - a.b = no
              - b.c = yes
            then:
              reply: you dont have A
          - case: b.c = xx
            then:
              reply: you dont have 
```

Getting quite complicated, almost worth considering inline JS?
or else the visual editor.
