### ISSUE TITLE
redo IF blocks

### ISSUE THREAD

**Issue by dcsan** [dcsan/xbot#35]
allow like a switch statement with IFs
remove 'all' qualifier

```yaml
- if: a = b.1

- if: c = 2
  reply: c = 3

# multiple conditions
- if: [ car.hot = yes, cop.is = here ]
  reply: bye!
  after: goHere

- if: [test1, test]
  reply: 1 and 2 ok

- if:
  - item.state = yes
  - item2.state = no
  reply: I dont care.

# multiple replies
- if: [a.b=1, a.c=2]
  reply: [a, few, things]

- if: x=1
  reply:
  - red
  - green
  - blue

# or conditions break apart as strings?
- if: x=1 || x =2
  reply: or cond met
```

```json
[
  {
    "if": "a = b.1"
  }, 
  {
    "reply": "c = 3", 
    "if": "c = 2"
  }, 
  {
    "reply": "bye!", 
    "after": "goHere", 
    "if": [
      "car.hot = yes", 
      "cop.is = here"
    ]
  }, 
  {
    "reply": "1 and 2 ok", 
    "if": [
      "test1", 
      "test"
    ]
  }, 
  {
    "reply": "I dont care.", 
    "if": [
      "item.state = yes", 
      "item2.state = no"
    ]
  }, 
  {
    "reply": [
      "a", 
      "few", 
      "things"
    ], 
    "if": [
      "a.b=1", 
      "a.c=2"
    ]
  }, 
  {
    "reply": [
      "red", 
      "green", 
      "blue"
    ], 
    "if": "x=1"
  }, 
  {
    "reply": "or cond met", 
    "if": "x=1 || x =2"
  }
]

```
