### ISSUE TITLE
webhooks for multiple bots

### ISSUE THREAD

**Issue by dcsan** [dcsan/xbot#50]
using webhooks, post text with an icon for each NPC

super-deluxe experience with multiple "speakers" - but only on our own server.
single 'bot' speaker (maybe with prefixes?) on other servers.
we'd also need to change the markup code to specify a bot so like:

```yaml
- say: What's up?
  actor: Dale
- say: We have a problem  
  actor: Chief
```
